packages:
  - "demo"
  - "docs"

allowBuilds:
  es5-ext: true
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - toolbox-x
  - nhb-scripts

minimumReleaseAge: 120

overrides:
  "vite@>=8.0.0 <9.0.0-0": "^8"
